/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appconceptos;

import javax.swing.JOptionPane;

/**
 *
 * @author Geovanny
 */
public class Frm_Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Ventana
     */
    Ficha objFicha = new Ficha();
    Tablero objTablero = new Tablero();
    
    public Frm_Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Txa_Impresion = new javax.swing.JTextArea();
        Txf_Numero = new javax.swing.JTextField();
        Btn_Salvar = new javax.swing.JButton();
        Btn_Impresion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Txa_ImpresionTablero = new javax.swing.JTextArea();
        Btn_GeneraTablero = new javax.swing.JButton();
        Btn_ImprimeTablero = new javax.swing.JButton();
        Cbo_BaseNumerica = new javax.swing.JComboBox<>();
        Txf_Busqueda = new javax.swing.JTextField();
        Btn_Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Txa_Impresion.setColumns(20);
        Txa_Impresion.setRows(5);
        jScrollPane1.setViewportView(Txa_Impresion);

        Btn_Salvar.setText("Salvar");
        Btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalvarActionPerformed(evt);
            }
        });

        Btn_Impresion.setText("Impresion");
        Btn_Impresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ImpresionActionPerformed(evt);
            }
        });

        Txa_ImpresionTablero.setColumns(20);
        Txa_ImpresionTablero.setRows(5);
        jScrollPane2.setViewportView(Txa_ImpresionTablero);

        Btn_GeneraTablero.setText("Genera Tablero");
        Btn_GeneraTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GeneraTableroActionPerformed(evt);
            }
        });

        Btn_ImprimeTablero.setText("Imprime Tablero");
        Btn_ImprimeTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ImprimeTableroActionPerformed(evt);
            }
        });

        Cbo_BaseNumerica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quinario", "Octal", "Decimal", "DuoDecimal", "Hexadecimal" }));

        Btn_Buscar.setText("Buscar");
        Btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Impresion)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Txf_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Salvar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cbo_BaseNumerica, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_ImprimeTablero)
                    .addComponent(Btn_GeneraTablero)
                    .addComponent(Txf_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Buscar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_GeneraTablero)
                        .addGap(41, 41, 41)
                        .addComponent(Cbo_BaseNumerica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_ImprimeTablero)
                        .addGap(18, 18, 18)
                        .addComponent(Txf_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Buscar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txf_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Salvar))
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Impresion)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalvarActionPerformed
        // TODO add your handling code here:
        objFicha.setNumDec(Integer.parseInt(Txf_Numero.getText()));
        

    }//GEN-LAST:event_Btn_SalvarActionPerformed

    private void Btn_ImpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ImpresionActionPerformed
        // TODO add your handling code here:
        Txa_Impresion.setText("");
        Txa_Impresion.append("" + objFicha.toString(Ficha.QUINARIO) + "\n");
        Txa_Impresion.append("" + objFicha.toString(Ficha.OCTAL) + "\n");
        Txa_Impresion.append("" + objFicha.toString(Ficha.DECIMAL) + "\n");
        Txa_Impresion.append("" + objFicha.toString(Ficha.DUODECIMAL) + "\n");
        Txa_Impresion.append("" + objFicha.toString(Ficha.HEXADECIMAL) + "\n");
        Txa_Impresion.append("" + objFicha.isSalio());
        

    }//GEN-LAST:event_Btn_ImpresionActionPerformed

    private void Btn_GeneraTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GeneraTableroActionPerformed
        // TODO add your handling code here:
        objTablero.GeneraTablero();

    }//GEN-LAST:event_Btn_GeneraTableroActionPerformed

    private void Btn_ImprimeTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ImprimeTableroActionPerformed
        // TODO add your handling code here:
        // Txa_ImpresionTablero.setText(objTablero.imprimeTablero());

        // QuinariO, Octal, Decimal, DuoDecimal, Hexadecimal
        int indiceCombo;
        String indiceNombre = "";
        int sistemaNumerico = 0;
        indiceCombo = Cbo_BaseNumerica.getSelectedIndex();
        /*  indiceNombre = (String) Cbo_BaseNumerica.getSelectedItem();
        if (indiceNombre.equalsIgnoreCase("Quinario")) {
            sistemaNumerico = Ficha.QUINARIO;
        }*/
        
        if (indiceCombo == 0) {
            sistemaNumerico = Ficha.QUINARIO;
        } else {
            if (indiceCombo == 1) {
                sistemaNumerico = Ficha.OCTAL;
            } else {
                if (indiceCombo == 2) {
                    sistemaNumerico = Ficha.DECIMAL;
                } else {
                    if (indiceCombo == 3) {
                        sistemaNumerico = Ficha.DUODECIMAL;
                    } else {
                        sistemaNumerico = Ficha.HEXADECIMAL;
                    }
                }
            }
        }
        Txa_ImpresionTablero.setText(objTablero.imprimeTablero(sistemaNumerico));

    }//GEN-LAST:event_Btn_ImprimeTableroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:


    }//GEN-LAST:event_formWindowOpened

    private void Btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarActionPerformed
        // TODO add your handling code here:
        
        if (objTablero.buscarFicha(Txf_Busqueda.getText())) {
            JOptionPane.showMessageDialog(null, "Encontrado");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontro en el sistema : "+Cbo_BaseNumerica.getSelectedItem());
        }

        
    }//GEN-LAST:event_Btn_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_GeneraTablero;
    private javax.swing.JButton Btn_Impresion;
    private javax.swing.JButton Btn_ImprimeTablero;
    private javax.swing.JButton Btn_Salvar;
    private javax.swing.JComboBox<String> Cbo_BaseNumerica;
    private javax.swing.JTextArea Txa_Impresion;
    private javax.swing.JTextArea Txa_ImpresionTablero;
    private javax.swing.JTextField Txf_Busqueda;
    private javax.swing.JTextField Txf_Numero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
