/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appconceptos;

import java.awt.Color;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicol
 */
public class tableframe extends javax.swing.JFrame {

    DefaultTableModel ObjTabla = new DefaultTableModel();
    // tableframe tf = new tableframe();

    /*
     * Creates new form tableframe
     */
    
    Ficha objFicha = new Ficha();
    Tablero objTablero = new Tablero();
    
    public tableframe() {
        initComponents();
        //------------------
        String titulo[] = {"B", "I", "T", "C", "O", "N"};
        ObjTabla.setColumnIdentifiers(titulo);
        Tbl_Bitcon.setModel(ObjTabla);
        //------------------
        // Establecer el color de fondo del JFrame
        getContentPane().setBackground(Color.WHITE);
        Tbl_Bitcon.setModel(ObjTabla);
        Tbl_Bitcon.changeSelection(0, ICONIFIED, false, false);
        
        // Agregar filas al modelo de la tabla con números aleatorios
        for (int DIM01 = 0; DIM01 < 6; DIM01++) {
            Object[] fila = new Object[6]; // Crear un array para una fila
            for (int DIM02 = 0; DIM02 < 6; DIM02++) {
                fila[DIM02] = 1; // Asignar el número aleatorio a la celda correspondiente
            }
            ObjTabla.addRow(fila); // Agregar la fila al modelo de la tabla
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_Bitcon = new javax.swing.JTable();
        icn_bitcon = new javax.swing.JButton();
        Cbo_SistemaNumerico = new javax.swing.JComboBox<>();
        Lbl_SisNumerico = new javax.swing.JLabel();
        Btn_Jugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BITCON");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setFont(new java.awt.Font("Agency FB", 3, 10)); // NOI18N
        setForeground(java.awt.Color.gray);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Tbl_Bitcon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        Tbl_Bitcon.getTableHeader().setResizingAllowed(false);
        Tbl_Bitcon.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Tbl_Bitcon);

        icn_bitcon.setForeground(new java.awt.Color(255, 255, 255));
        icn_bitcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appconceptos/BITCON.png"))); // NOI18N

        Cbo_SistemaNumerico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quinario", "Octal", "Decimal", "DuoDecimal", "Hexadecimal" }));

        Lbl_SisNumerico.setText("Sistema Numerico");

        Btn_Jugar.setText("Jugar");
        Btn_Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_JugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cbo_SistemaNumerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lbl_SisNumerico)
                            .addComponent(Btn_Jugar))
                        .addGap(158, 158, 158)
                        .addComponent(icn_bitcon, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icn_bitcon, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_SisNumerico)
                        .addGap(17, 17, 17)
                        .addComponent(Cbo_SistemaNumerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(Btn_Jugar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed


    }//GEN-LAST:event_formWindowClosed

    private void Btn_JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_JugarActionPerformed
        // TODO add your handling code here:
        int indiceCombo;
        String indiceNombre = "";
        int sistemaNumerico = 0;
        indiceCombo = Cbo_SistemaNumerico.getSelectedIndex();
        sistemaNumerico = switch (indiceCombo) {
            case 0 -> Ficha.QUINARIO;
            case 1 -> Ficha.OCTAL;
            case 2 -> Ficha.DECIMAL;
            case 3 -> Ficha.DUODECIMAL;
            default -> Ficha.HEXADECIMAL;
        };
    }//GEN-LAST:event_Btn_JugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tableframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tableframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tableframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tableframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tableframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Jugar;
    private javax.swing.JComboBox<String> Cbo_SistemaNumerico;
    private javax.swing.JLabel Lbl_SisNumerico;
    private javax.swing.JTable Tbl_Bitcon;
    private javax.swing.JButton icn_bitcon;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
